### ISSUE TITLE
Query with quote needs to be escaped and shouldn't

### ISSUE THREAD

**Issue by eric7472** [komoot/photon#308] opened 2018-01-26 15:30 UTC
Dear,

I am testing Photon for replacing Mapzen search. It looks great but I have some trouble with name that contains quote, for example : 

Search for : **Gare Routière d'Annecy**

query is : https://photon.komoot.de/api/?q=Gare%20Routi%C3%A8re%20d%27Annecy&limit=5&osm_tag=!boundary&lang=fr

returns is : "Gare Routière de Perrache", nothing to see with the expected result

Same with escape quote **Gare Routière d'\Annecy** 
query is : https://photon.komoot.de/api/?q=Gare%20Routi%C3%A8re%20d%5C%27Annecy&limit=5&osm_tag=!boundary&lang=fr

returns is : **Gare Routière d'Annecy** as expected but escaping input is not a good option...

With Mapzen the behavior is as expected without escaping the input search
query : https://search.mapzen.com/v1/autocomplete?text=Gare%20Routi%C3%A8re%20d%27Annecy&focus.point.lat=45.9015967854367&focus.point.lon=6.120586395263673&api_key=search-MKZrG6M

return is : **Gare Routière d'Annecy** as expected

Is there any workaround to fix that ?

Thanks.
Eric

**Comment by hbruch** [comment] 2018-01-28 11:30
I can confirm that `Gare Routière d'Annecy` is analyzed differently on index and on search time, which causes this issue: 

`	curl -XPOST 'localhost:9200/photon/_analyze?pretty' -H 'Content-Type: application/json' -d'
	{
	  "analyzer": "search_ngram",
	  "text": "Gare Routiere d'\''Annecy"
	}
	'
` 

returns 

```
...
{
      "token" : "d'annecy",
      "start_offset" : 14,
      "end_offset" : 22,
      "type" : "<ALPHANUM>",
      "position" : 2
}
...
```

while 
`	curl -XPOST 'localhost:9200/photon/_analyze?pretty' -H 'Content-Type: application/json' -d'
	{
	  "analyzer": "index_ngram",
	  "text": "Gare Routiere d'\''Annecy"
	}
	'
`

returns 

```
...
    {
      "token" : "d",
      "start_offset" : 14,
      "end_offset" : 15,
      "type" : "word",
      "position" : 12
    },
    {
      "token" : "a",
      "start_offset" : 16,
      "end_offset" : 17,
      "type" : "word",
      "position" : 13
    },
...
```

Root cause is that [edge_ngram](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html#_configuration_17) tokenizer in [index_settings.json](https://github.com/komoot/photon/blob/344c69458a8cb2a88358de53e4acba3d6cb0affd/es/index_settings.json#L50) is configured to keep digits and letters, so the input is split on whitespaces, punctuation chars and symbols (which IMO is fine), while the [standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html) used in the search_ngram analyzer only splits on whitespaces.

A fix would be to apply the punctuation char filter to the search_ngram analyzer and extend it's replace_patterns by single quotes and add `"replacement": " "` so all punctuation chars are replaced by a whitespace.

**Comment by eric7472** [comment] 2018-02-01 19:08
Thanks for your answer and for looking for a solution. I have forwarded this to the team in charge of the photon installation for my company.

**Comment by karussell** [comment] 2018-03-25 20:48
Is now merged

**Closed by karussell** 2018-03-25 20:48 UTC
