### ISSUE TITLE
Possible to filter result types

### ISSUE THREAD

**Issue by amnesia7** [komoot/photon#119] opened 2014-10-15 21:07 UTC
Is it possible (or could it be possible) to include a list of types to the search api so that it only returns establishments and addresses (as an example) since at the moment it brings back everything (including post boxes and tram stops for example)?

**Comment by christophlingg** [comment] 2015-01-08 09:24
duplicate of #68

**Closed by christophlingg** 2015-01-08 09:24 UTC

**Comment by amnesia7** [comment] 2015-03-20 21:55
@christophlingg sorry to comment on a closed issue but wasn't sure it was worth re-opening it. 
I don't think it was a post box that I found that time, I think it was a bus stop that I wasn't sure should be listed or not: 
http://photon.komoot.de/api/?q=London%20Eye,%20Belvedere%20Road,%20London,%20United%20Kingdom&limit=5

**Comment by christophlingg** [comment] 2015-03-23 08:51
our index contains basically everything that can be found in nominatim. searching for bus stops is a reasonable use case for me. would you expect something different?

**Comment by sdole** [comment] 2015-03-23 09:15
@amnesia7 have you tried the tag filters? https://github.com/komoot/photon/blob/master/README.md#filter-results-bhy-tags-and-values 
If you want specific items that you know osm tags for, you could search for just those. If you know specific tags, you wanted to exclude, you could exclude.

For the query you posted, you could modify like this to exclude bus stops:
http://photon.komoot.de/api/?q=London%20Eye,%20Belvedere%20Road,%20London,%20United%20Kingdom&limit=5&osm_tag=:!bus_stop

Does this help?

**Comment by amnesia7** [comment] 2015-03-23 19:57
@christophlingg yes, I can understand there may be a need to be able to search for so that's not an issue for me. I was just caught out by it when I couldn't find bus stops in the openstreetmap tags list but I've just had another look and realised that it is actually the value for the highway key rather than a key in its own right.
Thank you both.
@sdole I've just had a look at the query excluding the bus stops and its fine but I'm surprised it has London Road in Worcester higher up than several for Belvedere Road London.
