### ISSUE TITLE
Missing county, town and village in response in Photon responses

### ISSUE THREAD

**Issue by kurko** [komoot/photon#334] opened 2018-05-24 20:55 UTC
**Problem**: Nominatim includes `county`, `town`, `village` in its responses, whereas those are missing in Photon responses.

For instance, [q=135+pilkington+avenue,+birmingham](https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue,+birmingham&format=json) returns 

> display_name: "135, Pilkington Avenue, Sutton Coldfield, Birmingham, West Midlands Combined Authority, West Midlands, England, B72 1LH, United Kingdom"

The Photon omits `Sutton Coldfield`, `West Midlands Combined Authority` and`West Midlands`, returning the following corresponding data:

```
country: "United Kingdom",
housenumber: "135",
city: "Birmingham",
street: "Pilkington Avenue",
postcode: "B72 1LH",
state: "England"
```

Is this by design? Looking at the [code](https://github.com/komoot/photon/blob/ad55523f901041f1519713ad1744fb8697b3da0b/src/main/java/de/komoot/photon/importer/XMLExporter.java#L43-L69) it's not even being imported. I'm wondering if this feature would be welcome by the core team.

**Comment by lonvia** [comment] 2018-06-28 20:30
It is possible to add those but not as simple as it seems because the information that would actually be useful to add varies from country to country. Nominatim is cheating here. It just takes all relevant administrative boundaries it can find and strings their name together. For photon, we'd actually need something like `county=foo`. The information which boundary is which kind of place entity is really bad at the moment. Just browse through the numerous tickets in Nominatim about bad addresses. This needs to be fixed, before photon can get more detailed information.

In any case, closing as duplicate of #120.

**Closed by lonvia** 2018-06-28 20:30 UTC
