### ISSUE TITLE
GB post code results worse than postcodes.io (open source/open data service)

### ISSUE THREAD

**Issue by smithfred** [komoot/photon#593] opened 2021-07-05 17:49 UTC
Photon fails to find results for post codes that are found by postcodes.io, which uses purely open data from the following sources (per https://postcodes.io/about):

* ONS Postcode Directory
* OS Open Names
* Scottish Postcode Directory

Photon should use, and be able to find every post code available in, those data sets, as postcodes.io does/can.

Example:

https://api.postcodes.io/postcodes/DT6%203JP (successful).

https://photon.komoot.io/api/?q=DT6%203JP (fails).

Downstream GNOME Maps bug: https://gitlab.gnome.org/GNOME/gnome-maps/-/issues/84

**Comment by lonvia** [comment] 2021-07-05 19:23
Duplicate of #310.

**Closed by lonvia** 2021-07-05 19:23 UTC
