### ISSUE TITLE
Specify terms of use

### ISSUE THREAD

**Issue by debuglevel** [komoot/photon#549] opened 2021-03-16 20:24 UTC
It would be nice to know what "fair" and "extensive" usage looks like :).
I've got two projects of me in mind: The first does a bulk request of 60 addresses. Nominatim would already request to throttle that to 1 request per second. The second would require an initial bulk request of 5000 addresses and then maybe 30 requests each day.

I wonder therefore if I should implement some caching and throttling in my application or if the elasticsearch backend of photon would not even notice it ;-).

**Comment by lonvia** [comment] 2021-03-16 20:43
Duplicate of #479.

To add to the answer there: if you do have to use the server for bulk requests make sure to run them sequentially.

**Closed by lonvia** 2021-03-16 20:43 UTC
