### ISSUE TITLE
Unknown query parameter 'bbox'

### ISSUE THREAD

**Issue by Zvorykin** [komoot/photon#440] opened 2019-10-17 19:24 UTC
Got that message using photon 0.3.1 quering readme example
`http://localhost:2322/api?q=berlin&bbox=9.5,51.5,11.5,53.5`

```
{
    "message": "unknown query parameter 'bbox'. 
Allowed parameters are: [q, location_bias_scale, limit, osm_tag, lon, lang, lat]"
}
```

**Comment by MvRemmerden** [comment] 2019-10-18 03:16
Duplicate of https://github.com/komoot/photon/issues/431.

Would love to see a new release soon with bbox working, looking forward to it a lot :)

**Comment by lonvia** [comment] 2019-10-18 16:59
Yeah, we probably should do another release this year.

**Closed by lonvia** 2019-10-18 16:59 UTC

**Comment by MvRemmerden** [comment] 2019-10-18 20:30
That would be very much appreciated, I currently use it in production for https://gymlist.de and having the option to limit the results to this bounding box would be an amazing improvement!
