### ISSUE TITLE
Address returns wrong search result

### ISSUE THREAD

**Issue by jmvx** [komoot/photon#244] opened 2017-03-03 20:18 UTC
If you search for: 2 Main Street, Redwood City, CA
The top search result is not the specified address. It's too general:
Main Street 94063 Redwood City United States of America
`http://0.0.0.0:2322/api/?q="2%20Main%20Street,%20Redwood%20City,%20CA"`

If you search for 5 Main Street, Redwood City, CA
The top search result is in the Philippines:
5th Main Street 5000 Jaro Philippines
`http://0.0.0.0:2322/api/?q="5%20Main%20Street,%20Redwood%20City,%20CA"`

**Comment by karussell** [comment] 2017-03-03 20:33
The problem here might be the missing interpolation of house addresses in case that the underlying data has no such data. E.g. if you search "1531 Main Street, Redwood City, CA" this seems to be ok.

**Comment by lonvia** [comment] 2021-06-16 08:43
Duplicate of #204.

**Closed by lonvia** 2021-06-16 08:43 UTC
