### ISSUE TITLE
Feature request: Intersections

### ISSUE THREAD

**Issue by etiennebr** [komoot/photon#245] opened 2017-04-04 15:35 UTC
I was wondering if there was a way to geocode intersections using typical `street & street, ...` notation (supported by e.g. Google Maps or ESRI geocoding). I gave it a try using the demo, but it seems like it only settles on one of the two streets. 

Maybe there's a way to achieve this using a different notation? Otherwise I believe it would be a nice feature to add.

**Comment by lonvia** [comment] 2020-12-24 11:15
Duplicate of #203.

**Closed by lonvia** 2020-12-24 11:15 UTC
