### ISSUE TITLE
Release photon to maven central repository

### ISSUE THREAD

**Issue by intfrr** [komoot/photon#530] opened 2021-01-22 18:31 UTC
Hi guys,

I know there is an issue from 2018 about this but I think it would help a lot to get more visibility by releasing in the maven central repository.

What do you think?

Regards

**Comment by karussell** [comment] 2021-01-22 18:36
Sure, this would be nice. Still requesting an existing issue does not necessarily improve the situation :) 

Closing as a duplicate of #280.

**Closed by karussell** 2021-01-22 18:36 UTC
