### ISSUE TITLE
Exact match disappears down results

### ISSUE THREAD

**Issue by systemed** [komoot/photon#270] opened 2017-11-25 12:26 UTC
Searching for 'Tottenham Road' on Nominatim (http://nominatim.openstreetmap.org/search.php?q=Tottenham+Road&polygon_geojson=1&viewbox=) correctly returns the road in London: http://www.openstreetmap.org/way/463657968

Searching in Photon, however (http://photon.komoot.de/api?q=Tottenham+Road), returns only several instances of Tottenham Court Road - a different but more major road - plus a number of Tottenham Roads elsewhere. The London Tottenham Road is returned in 20th place if &limit=20 is specified.

Nominatim and Photon having such vastly different ordering for an exact match seems odd.

**Comment by karussell** [comment] 2017-11-25 13:42
> Nominatim and Photon having such vastly different ordering for an exact match seems odd.

It is a completely different software so this does not come as a surprise

**Comment by agastya71** [comment] 2017-11-25 14:54
Nominatim is based off a relational database and search/retrieval  performs
differently compared to Photon based on Elasticsearch.  I have recently run
into a similar issue in a different use case.  The reason for Tottenham
Road not showing up is most probably due to the similarity  scores and how
they are calculated in ES.

I would be very interested in getting a more thorough explanation tho'.

Ramdev

**Comment by lonvia** [comment] 2021-06-16 08:37
Closing as duplicate of #277.

**Closed by lonvia** 2021-06-16 08:37 UTC
