### ISSUE TITLE
feedback 0.2.1

### ISSUE THREAD

**Issue by christophlingg** [komoot/photon#142] opened 2015-02-10 13:10 UTC
The next version 0.2.1 was just released on photon.komoot.de, it contains the brand new feature of @sdole that allows filtering results on `osm_key` and `osm_value`, see [readme](https://github.com/komoot/photon/#filter-results-by-tags-and-values).

It should also resolve all the new issues that popped up with the data concerning missing city assignments and wrong importance data. see #134, #138 and partially #135.

However, local knowledge is needed to assure correctness of our word-wide data. If you have some time, please check out the search data on report issues here.

**Comment by christophlingg** [comment] 2015-02-10 13:32
copenhagen cannot be found: http://photon.komoot.de/api?q=copenhagen&debug which is a mistery because the document is correctly created and has a very high importance. Searching for the danish version works: http://photon.komoot.de/api?q=K%C3%B8benhavn&debug

**Comment by christophlingg** [comment] 2015-02-10 13:41
however, this is the only bug i could found during my research

**Comment by amnesia7** [comment] 2015-02-15 00:56
Not sure if it relates to the update or not but if I search for `eiffel tow` then Eiffel Tower, Paris appears top of the list but as soon as I continue typing `eiffel towe` or `eiffel tower` then it no longer appears (at least in the top 5 using photon.komoot.de demo). If I continue typing `eiffel tower paris` it only lists a single item which is Eiffel Tower Lane in USA.

**Comment by christophlingg** [comment] 2015-02-16 09:36
I found a for which i do not know if it is a bug ;-) Here is an example of an address that has a `city` tag: `addr:city	Bad Hall` http://www.openstreetmap.org/node/528275583

After importing it from nominatim the city has changed and is now `Kremsmünster`: http://photon.komoot.de/api?q=haid+4+kremsm%C3%BCnster&debug

The city information got overwritten by nominatim, which seems to be fine, at least google maps is approving that Kremsmünster is correct.

**Comment by lonvia** [comment] 2015-02-16 10:09
addr:city information on address nodes is ignored by nominatim. That's a known issue that requires some changes in the database schema to fix.

**Comment by amnesia7** [comment] 2015-02-17 19:40
Strangely, `Eiffel Tower, Paris, France` appears in the results again if I continue typing france `eiffel tower paris france`. Not sure where it goes between times.

**Comment by karussell** [comment] 2015-02-23 08:57
Very impressive release :+1: 

I've integrated it on graphhopper maps, so that the destination uses the start as a location hint and no need to retype e.g. the city, which is ... magically, wow :)

Some minor things (I'll edit/add more if I found more in the next days)

 * The city 'hof' comes at 2nd place (before there is a village (?) 'hof')
 * The city 'bayreuth' comes at 2nd place (before there is 'bayreuth hauptbahnhof')

The only important issue for me to fix is the #46 :)

**Comment by christophlingg** [comment] 2015-02-23 09:52
Thanks for your feedback and keep on reporting. I also found some strange importance calculation coming from nominatim, see https://github.com/twain47/Nominatim/issues/236 and maybe @mtmail will investigate further on it. nominatim does not depend as much on a correct importance value (the often use exact matches on name). that's why these kind of problems pop up in photon first

**Comment by amnesia7** [comment] 2015-03-27 22:08
@christophlingg did you manage to figure out what was up with the `copenhagen` and `eiffel tower` issues mentioned above?

**Comment by amnesia7** [comment] 2015-04-18 09:32
@christophlingg I can see the instructions on the readme of how to setup my own installation of photon for worldwide coverage but I don't have the capacity for that and wondered if there was a smaller subset of data available that can I can use so that I can try looking into the city names issue mentioned above...unless you already have an idea what the issue is anyway.

**Comment by amnesia7** [comment] 2015-06-05 16:58
@christophlingg I was wondering if you had any time free soon to be able to continue with the photon project so that progress can be made with the milestone 0.3 items or maybe just to resolve the issue where city isn't being indexed correctly (it's a shame to leave such a great project in a [slightly] broken state)?

@sdole @karussell @daryltucker (trying not to spam but wondered if any of you could offer any help) have you any ideas about the current/outstanding issues affecting photon v0.2?

Just hoping to drum-up some movement on this project again...

**Comment by amnesia7** [comment] 2015-07-03 22:13
Just to link them to this issue - the `eiffel tower` / `copenhagen` issues mentioned above now appear to have been fixed by https://github.com/komoot/photon/issues/171 and https://github.com/komoot/photon/pull/173

**Comment by karussell** [comment] 2017-10-31 10:52
All problems mentioned here are fixed

**Closed by karussell** 2017-10-31 10:52 UTC
