### ISSUE TITLE
Reverse geocoding less accurate compared to Nominatim

### ISSUE THREAD

**Issue by avshabavsha** [komoot/photon#626] opened 2022-01-03 10:49 UTC
Hello,

I noticed in some of the reverse geocoding queries I do, the returned feature (e.g. street name) is not always accurate.

Searching the same lat/lon gave different result between Photon and Nominatim (the street in Nominatim was correct).

Taking into account Photon's data is migrated from Nominatim, I would expect that the accuracy would be consistent - both would either be wrong or be right. 

I both checked photon result with the public https://photon.komoot.io, and ran locally using latest data (specifically in this case of Greece). In both I got the wrong address as the top result.

I am trying to understand the gap, and see if there's some change in query that can be done to make the photon result more accurate. 
The only thought I had is that maybe during migration to photon, the street geometry is stored as a the a point which is the center of each street and not as a LineString?

### Visual Explanation
To understand better what is returned from Photon, I made the call with limit of 20 to see the features found in the wanted area (pasted in geojson.io).
I've marked the coordinates location I looked at, which features returned and the feature which is considered the closest.
![image](https://user-images.githubusercontent.com/36112996/147919694-b86b2144-247b-41fa-9100-016868ecd2f7.png)

### Comparison between Photon and Nominatim calls (notice the returned name):
**Photon**
https://photon.komoot.io/reverse?lon=23.90427952592436&lat=38.032463599743316&lang=default
{
    "features": [{
            "geometry": {
                "coordinates": [23.903924, 38.0336909],
                "type": "Point"
            },
            "type": "Feature",
            "properties": {
                "osm_id": 63853942,
                "extent": [23.9021816, 38.034418, 23.9064719, 38.0329742],
                "country": "Ελλάς",
                "city": "Δημοτική Ενότητα Πικερμίου",
                "countrycode": "GR",
                "postcode": "153 51",
                "county": "Περιφερειακή Ενότητα Ανατολικής Αττικής",
                "type": "street",
                "osm_type": "W",
                "osm_key": "highway",
                "district": "Ντράφι",
                "osm_value": "residential",
                **"name": "Πυθαγορα",**
                "state": "Αποκεντρωμένη Διοίκηση Αττικής"
            }
        }
    ],
    "type": "FeatureCollection"
}

**Nominatim**
https://nominatim.openstreetmap.org/reverse?lon=23.90427952592436&lat=38.032463599743316&accept-language=default&format=geojson
{
    "type": "FeatureCollection",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
    "features": [{
            "type": "Feature",
            "properties": {
                "place_id": 117494205,
                "osm_type": "way",
                "osm_id": 62092990,
                "place_rank": 26,
                "category": "highway",
                "type": "tertiary",
                "importance": 0.09999999999999998,
                "addresstype": "road",
                **"name": "Αιολέων",**
                "display_name": "Αιολέων, Ντράφι, Κοινότητα Πικερμίου, Δημοτική Ενότητα Πικερμίου, Δήμος Ραφήνας - Πικερμίου, Περιφερειακή Ενότητα Ανατολικής Αττικής, Περιφέρεια Αττικής, Αποκεντρωμένη Διοίκηση Αττικής, 153 51, Ελλάς",
                "address": {
                    "road": "Αιολέων",
                    "suburb": "Ντράφι",
                    "city_district": "Κοινότητα Πικερμίου",
                    "city": "Δημοτική Ενότητα Πικερμίου",
                    "municipality": "Δήμος Ραφήνας - Πικερμίου",
                    "county": "Περιφερειακή Ενότητα Ανατολικής Αττικής",
                    "state_district": "Περιφέρεια Αττικής",
                    "state": "Αποκεντρωμένη Διοίκηση Αττικής",
                    "postcode": "153 51",
                    "country": "Ελλάς",
                    "country_code": "gr"
                }
            },
            "bbox": [23.8949478, 38.0324145, 23.9055246, 38.0344383],
            "geometry": {
                "type": "Point",
                "coordinates": [23.904281013355874, 38.03248857205444]
            }
        }
    ]
}

### Used versions:
photon version: 0.3.5
downloaded data (28-Dec-2021): https://download1.graphhopper.com/public/extracts/by-country-code/gr/photon-db-gr-latest.tar.bz2

Thank you,
Avshalom

**Comment by lonvia** [comment] 2022-01-03 14:12
Photon does not store complete geometries for its features but just the bounding boxes. The accuracy of reverse geocoding is limited by that. See also #357 for more discussion on that.

**Comment by lonvia** [comment] 2022-03-18 15:23
Closing as duplicate of #357.

**Closed by lonvia** 2022-03-18 15:23 UTC
