### ISSUE TITLE
Location Based Search not working when using planet osm

### ISSUE THREAD

**Issue by ajinra020307** [komoot/photon#488] opened 2020-09-08 06:27 UTC
os: debian
photon-version :: 0.3.1
java-version :: 1.8

We imported planet osm data using nominatim and uses photon.

When trying to search for a location using lat, lon and location_bias_scale. It is giving out results which are far away from the location we gave(other country).

What may me the problem for this issue?

**Comment by mtmail** [comment] 2020-09-08 13:32
Can you add one or more specific examples? Do you see the same on https://photon.komoot.de/ ?

**Comment by ajinra020307** [comment] 2020-09-20 07:50
I checked on photon api, the same problem

`http://photon.komoot.de/api?q=che&lang=en&lon=80.252811&lat=13.075180&location_bias_scale=1`

In above url i pass the lat lon of India,Chennai.But it does not gives results nearby

**Comment by lonvia** [comment] 2020-09-22 07:17
Duplicate of #430.

**Closed by lonvia** 2020-09-22 07:17 UTC
