### ISSUE TITLE
case sensitive search

### ISSUE THREAD

**Issue by ccloquet** [komoot/photon#225] opened 2016-05-20 16:18 UTC
I am using photon from Leaflet, and it is working great. Just one detail : the search is case sensitive for letters that are inside the words (no influence of the case for the first letter of a word)

**Comment by karussell** [comment] 2016-06-08 12:39
Do you have an example? Do you mean camelCase?

**Comment by ccloquet** [comment] 2016-06-17 09:41
Yes, for instance : restoJet vs restojet

The former leads to results, and in particular a social_facility in Jette, the latter leads to no results

**Comment by karussell** [comment] 2016-06-22 19:52
I have an example: [techbase regensburg](http://photon.komoot.de/api/?q=techbase%20regensburg&limit=2&debug) vs. [TechBase regensburg](http://photon.komoot.de/api/?q=TechBase%20regensburg&limit=2&debug)

**Comment by christophlingg** [comment] 2016-07-06 13:48
must be related to a [token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html) that splits `TechBase` into two terms `tech` + `base`

**Comment by karussell** [comment] 2017-10-31 10:40
I think this is a duplicate of #42

**Comment by karussell** [comment] 2017-10-31 10:40
Ah but not the same

**Comment by hbruch** [comment] 2018-01-05 04:33
Before lowercasing the address terms, photon applies an ES word delimiter token filter. It splits terms at case transitions so restoJet becomes resto and jet.

Preserving the original term via preserve_original, at least for the index analyzer, might help here.

**Comment by lonvia** [comment] 2020-12-24 11:13
Seems to be working in the meantime.

**Closed by lonvia** 2020-12-24 11:13 UTC
