### ISSUE TITLE
city name from zipcode?

### ISSUE THREAD

**Issue by klml** [komoot/photon#243] opened 2017-01-31 22:08 UTC
Is it possible get the city name from zipcode?

For adress forms I would like to prefill the city after typed in the zipcode for one specific country. When I fill in '80331' I want to have 'München'.

I tried it with tags http://photon.komoot.de/api/?q=80331&lat=48&lon=11&osm_tag=:Germany&osm_tag=:town&lang=de , but got too much,

**Comment by agastya71** [comment] 2017-01-31 22:26
I am not sure  if it can be done the way you seek it.  The query field is looking for a String match to 80331 and so matches with all postal codes (which are stored as Strings) that begin with 803.  Unless the data is indexed with the possibility of exact string matches, you will get more than what you asked for.

**Comment by klml** [comment] 2017-01-31 22:44
Is there a plan to extend photon, or is there another (osm)-service to get citynames from zipcodes?

**Comment by agastya71** [comment] 2017-01-31 22:57
the nominatim/openstreetmap service can do what Photon does.  and it does return Munich as the top result, but it does return more than just one result
http://www.openstreetmap.org/search?query=80331#map=5/51.522/-7.778

**Comment by lonvia** [comment] 2017-02-02 19:01
http://nominatim.openstreetmap.org/search?postalcode=80331&country_codes=de would be the more fitting query for Nominatim. But, please, please, be aware that postcode coverage in OSM is shaky at best and Nominatim's handling of it even worse. It's a known issue and somewhere on the todo list.

**Comment by hbruch** [comment] 2018-01-29 09:07
To retrieve city names for a given postal code, you could try:

http://photon.komoot.de/api/?q=80331%20&osm_tag=place:postcode&lang=de

This returns a postal code relation and the estimated center of the postal code area. Photon relies on Nominatim to calculate these. For details see @lonvia's blog '[Nominatim and Postcodes](http://www.openstreetmap.org/user/lonvia/diary/43143)'.

**Comment by lonvia** [comment] 2021-06-16 08:42
We; d need to import postcodes from Nominatim. As such, duplicate of #310.

**Closed by lonvia** 2021-06-16 08:42 UTC
