### ISSUE TITLE
Photon hangs randomly 

### ISSUE THREAD

**Issue by gerbsen** [komoot/photon#207] opened 2015-12-07 14:03 UTC
Hello,
We started to experience a strange behavior of photon lately. We have three endpoints (0.2.5) configured behind a Load-Balancer. After a while all the endpoints are down because of this error:

```
[qtp773655192-5130] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[ehDnaztrRT-u0ds5TZ6yFw][photon][0]: QueryPhaseExecutionException[[photon][0]: query[filtered(function score (+((collector.default:osl~1 collector.en.ngrams:osl~1)~1) name.en.raw:osl^200.0 collector.en.raw:osl^100.0, functions: [{filter(*:*), function [script[general-score], params [null]]}{filter(*:*), function [script[location-biased-score], params [{lon=11.0797119140625, lat=60.18386720911798}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:osl) cache(BooleanFilter(_field_names:name.en.raw))],from[0],size[5]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[ehDnaztrRT-u0ds5TZ6yFw][photon][1]: QueryPhaseExecutionException[[photon][1]: query[filtered(function score (+((collector.default:osl~1 collector.en.ngrams:osl~1)~1) name.en.raw:osl^200.0 collector.en.raw:osl^100.0, functions: [{filter(*:*), function [script[general-score], params [null]]}{filter(*:*), function [script[location-biased-score], params [{lon=11.0797119140625, lat=60.18386720911798}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:osl) cache(BooleanFilter(_field_names:name.en.raw))],from[0],size[5]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[ehDnaztrRT-u0ds5TZ6yFw][photon][2]: QueryPhaseExecutionException[[photon][2]: query[filtered(function score (+((collector.default:osl~1 collector.en.ngrams:osl~1)~1) name.en.raw:osl^200.0 collector.en.raw:osl^100.0, functions: [{filter(*:*), function [script[general-score], params [null]]}{filter(*:*), function [script[location-biased-score], params [{lon=11.0797119140625, lat=60.18386720911798}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:osl) cache(BooleanFilter(_field_names:name.en.raw))],from[0],size[5]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[ehDnaztrRT-u0ds5TZ6yFw][photon][3]: QueryPhaseExecutionException[[photon][3]: query[filtered(function score (+((collector.default:osl~1 collector.en.ngrams:osl~1)~1) name.en.raw:osl^200.0 collector.en.raw:osl^100.0, functions: [{filter(*:*), function [script[general-score], params [null]]}{filter(*:*), function [script[location-biased-score], params [{lon=11.0797119140625, lat=60.18386720911798}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:osl) cache(BooleanFilter(_field_names:name.en.raw))],from[0],size[5]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[ehDnaztrRT-u0ds5TZ6yFw][photon][4]: QueryPhaseExecutionException[[photon][4]: query[filtered(function score (+((collector.default:osl~1 collector.en.ngrams:osl~1)~1) name.en.raw:osl^200.0 collector.en.raw:osl^100.0, functions: [{filter(*:*), function [script[general-score], params [null]]}{filter(*:*), function [script[location-biased-score], params [{lon=11.0797119140625, lat=60.18386720911798}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:osl) cache(BooleanFilter(_field_names:name.en.raw))],from[0],size[5]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Each of the endpoints has 6GB of RAM. Any ideas?

Cheers,
Daniel

**Comment by christophlingg** [comment] 2015-12-08 14:05
Ups a NullPointerException in Groovy .... It sounds like a document field got accessed that is not available (any more). I have not experienced this behaviour on my instances. Are you sure that nobody changes / deletes the index?

**Comment by gerbsen** [comment] 2015-12-15 07:37
I think so. We download & unpack the indexes from komoot. We only make geocoding and reverse geocoding requests (does that modify the index). We are downloading the index files again and will keep you posted. We think this is probably not the problem since we would have a corrupted download on 3 machines. By the way, does Komoot provide checksums?

**Comment by karussell** [comment] 2015-12-15 09:27
I can confirm and reproduce this - see the dup #208

**Comment by karussell** [comment] 2015-12-15 09:30
Hmmh, but our machines keep up and stable, just an exception and one failed request.

**Comment by karussell** [comment] 2015-12-15 09:39
Could the problem be [here](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/nominatim/NominatimConnector.java#L66)? As the centroid can be indeed empty!

But I currently do not understand where the field name changes from `centroid` to `coordinate`.

If that is really the cause then either we mark those objects also as `!isUsefulForIndex` or we throw an Exception if null instead of returning null.

**Comment by christophlingg** [comment] 2015-12-15 11:02
entries without a geometry are not useful for geocoder, so we can skip those without being concerned. I committed a fix for this into master. could you use this version to make the next import @karussell

**Closed** 2015-12-15 11:02 UTC

**Comment by karussell** [comment] 2015-12-15 11:12
Thanks - this will be used for the next import! 

Would you point me to the conversion step from `centroid` to `coordinate`?

**Comment by christophlingg** [comment] 2015-12-15 11:29
sure, [here](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/elasticsearch/Importer.java#L37) the document from Nominatim is received by the Photon Importer and later it [get's converted](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/Utils.java#L33) to a elasticsearch document where the field is renamed to coordinate.

**Comment by karussell** [comment] 2015-12-15 11:35
Thanks  (didn't found it as my text search was limited to xml files ;()

**Comment by lonvia** [comment] 2015-12-15 12:05
I don't remember exactly in which cases centroid is missing but it might be a better fix to fall back to point geometry if the centroid is null.

**Comment by karussell** [comment] 2015-12-15 12:25
What about logging these problematic documents to find out the reason?
