### ISSUE TITLE
Reverse geo encoding filtered by tags

### ISSUE THREAD

**Issue by dve** [komoot/photon#480] opened 2020-07-14 09:33 UTC
In my use case reverse geo encoding should not give an address, rather a wider geographic description like a landmark, nature reserve or village.

My suggestion would be no allow also the reverse endpoint to use the `osm_tag` parameter.

Would you accept a pr for this feature?

**Comment by lonvia** [comment] 2020-07-14 11:04
Duplicate of #224.  To quote the answer from there:

> You can do this now with the query_string_filter parameter, e.g. http://photon.komoot.de/reverse?lat=52.9112327&lon=-1.4786067&query_string_filter=osm_key:highway

**Closed by lonvia** 2020-07-14 11:04 UTC
